-- =============================================================================
-- SEGURIDAD SALT - ESQUEMA DE BASE DE DATOS (SUPABASE)
-- Tabla de Bitácora y Registro de Cotizaciones
-- =============================================================================

-- 1. Crear la tabla principal de cotizaciones
CREATE TABLE IF NOT EXISTS public.cotizaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    full_name TEXT NOT NULL,
    client_type TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    service_type TEXT,
    comments TEXT,
    status TEXT DEFAULT 'Pendiente',
    notes TEXT
);

-- 2. Habilitar Seguridad a Nivel de Filas (Row Level Security - RLS)
ALTER TABLE public.cotizaciones ENABLE ROW LEVEL SECURITY;

-- 3. Política: Permitir que cualquier visitante del sitio web inserte su cotización
CREATE POLICY "Permitir insercion anonima de cotizaciones"
ON public.cotizaciones
FOR INSERT
TO anon
WITH CHECK (true);

-- 4. Política: Permitir consultar la bitácora desde la web (bitacora.html) o panel admin
CREATE POLICY "Permitir lectura de cotizaciones"
ON public.cotizaciones
FOR SELECT
TO anon, authenticated
USING (true);

-- 5. Índices de optimización para consultas rápidas
CREATE INDEX IF NOT EXISTS idx_cotizaciones_created_at ON public.cotizaciones (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cotizaciones_service ON public.cotizaciones (service_type);

-- Comentario descriptivo
COMMENT ON TABLE public.cotizaciones IS 'Bitácora oficial de solicitudes de cotización recibidas desde el sitio web de Seguridad SALT';
